# Text analysis with Transcripts {#textcolor}

- Participants of the first study were allowed to take notes while reading through the transcripts, which are saved by page number
- We would like to use this to highlight which parts of the testimonies the participants found to be important

- First attempt:
  - ggplot: allows for both a gradient and transparency to be added to words based on their frequency
  - graphing words of the transcript resulted in ugly spacing
  - Relative frequency was computed based on the number of times the word appeared on the page
- Second attempt:
  - Using LaTex instead of ggplot: can set gradient through color outputted by ggplot, but have not played with transparency
  - Words can be equally spaced
  - Currently assigning a new color to each word - this is not efficient
  - Now in CSS for tab format
  - Labels added with gradient scale
  - Change from relative frequency to a different type of frequency
     - Cosine Similarity?
       - Jessica Recommended
     - Edit Distance?
       - Usually at the character level, not at the word level
       - Pay attention to what words/phrases show up often (not just final number)
     - On another note - could we use something like TurnItIn to determine which pages of the transcript were the most impactful?
       - Rabin-Karp algorithm?
       - Levenshtein distance?
       - http://users.csc.calpoly.edu/~dekhtyar/448-Spring2013/lectures/lec03.448.pdf
       - Maybe start by sentence level in transcript, then search notes for close-ish matching text
       